version: "3.5"

services:

    php:
        build:
            context: php
        ports:
        - 80:80
        volumes:
        - ./app:/var/www/html

    mariadb:
        image: mariadb:10.4
        ports:
        - 127.0.0.1:3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: DockerTest
            MYSQL_USER: TestUser
            MYSQL_PASSWORD: TestPass
        volumes:
            - ./database/mariadb:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - 127.0.0.1:8080:8080
        environment: 
            PMA_HOST: mariadb
            PMA_USER: TestUser
            PMA_PASSWORD: TestPass